// Generate src/resources/connector_icons.ts from Simple Icons.
//
// The connector marks are the only saturated pixels in the console - that is
// the whole reason the rest of the UI has no accent, so the eye lands on what
// a task touches. A grey monogram does not do that job.
//
// Simple Icons rather than each vendor's brand kit: its SVG path data is
// CC0, so it can live in this repo. The marks are still the trademarks of
// their owners, and are used here to identify the service each connector
// talks to - which is what they are for.
//
// Not every service is in it. Several were removed from Simple Icons on
// request from the trademark holder, and tracing a replacement by hand would
// be doing exactly the thing they asked not to be done. Those connectors fall
// back to a monogram tile, and a user who has the rights to a mark can drop
// one into branding/connectors/<id>.svg and it wins over both.
//
// Output is committed. The build machine needs no npm - same rule as
// branding/icons.
//
//   node tools/build-connector-icons.mjs

import * as si from 'simple-icons';
import {readFileSync, writeFileSync, existsSync, readdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, join} from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

// connector id -> Simple Icons slug. Only where the mark actually exists;
// everything absent from here renders as a monogram on purpose.
const SLUGS = {
  google: 'google',
  slack: 'slack',
  imessage: 'imessage',
  quickbooks: 'quickbooks',
  notion: 'notion',
  linear: 'linear',
  stripe: 'stripe',
  atlassian: 'atlassian',
  asana: 'asana',
  sentry: 'sentry',
  cloudflare: 'cloudflare',
  zapier: 'zapier',
  webflow: 'webflow',
  github: 'github',
  hubspot: 'hubspot',
  calendly: 'calendly',
  airtable: 'airtable',
  salesforce: 'salesforce',
  brex: 'brex',
  cal_com: 'caldotcom',
  coda: 'coda',
  posthog: 'posthog',
  sanity: 'sanity',
  google_analytics: 'googleanalytics',
  instagram: 'instagram',
  facebook_pages: 'facebook',
  basecamp: 'basecamp',
};

const bySlug = new Map();
for (const key of Object.keys(si)) {
  const icon = si[key];
  if (icon && icon.slug) bySlug.set(icon.slug, icon);
}

const connectors =
    JSON.parse(readFileSync(join(ROOT, 'src/resources/connectors.json'), 'utf8'))
        .connectors;

// A mark the user supplied themselves wins: they own the rights decision.
const OVERRIDE_DIR = join(ROOT, 'branding/connectors');
const overrides = new Map();
if (existsSync(OVERRIDE_DIR)) {
  for (const file of readdirSync(OVERRIDE_DIR)) {
    if (!file.endsWith('.svg')) continue;
    const svg = readFileSync(join(OVERRIDE_DIR, file), 'utf8');
    const paths = [...svg.matchAll(/\bd="([^"]+)"/g)].map(m => m[1]);
    if (!paths.length) {
      console.error(`    SKIP  ${file} has no <path d="...">`);
      continue;
    }
    const viewBox = (svg.match(/viewBox="([^"]+)"/) || [, '0 0 24 24'])[1];
    const hex = (svg.match(/fill="#([0-9a-fA-F]{6})"/) || [, '000000'])[1];
    overrides.set(file.replace(/\.svg$/, ''), {
      path: paths.join(' '),
      hex: hex.toUpperCase(),
      viewBox,
    });
  }
}

const entries = [];
const missing = [];
for (const connector of connectors) {
  const own = overrides.get(connector.id);
  if (own) {
    entries.push([connector.id, own, 'branding/connectors']);
    continue;
  }
  const slug = SLUGS[connector.id];
  const icon = slug ? bySlug.get(slug) : undefined;
  if (!icon) {
    missing.push(connector.id);
    continue;
  }
  entries.push([
    connector.id,
    {path: icon.path, hex: icon.hex, viewBox: '0 0 24 24'},
    `simple-icons:${slug}`,
  ]);
}

const body = entries
    .map(([id, icon, source]) =>
             `  // ${source}\n  ${JSON.stringify(id)}: {\n` +
             `    path: ${JSON.stringify(icon.path)},\n` +
             `    hex: ${JSON.stringify(icon.hex)},\n` +
             `    viewBox: ${JSON.stringify(icon.viewBox)},\n  },`)
    .join('\n');

const out = `// Copyright 2026 Flux. Based on Chromium, Copyright The Chromium Authors.
//
// GENERATED by tools/build-connector-icons.mjs - do not edit by hand.
//
// Brand marks for the connector catalogue. Path data from Simple Icons, which
// is CC0; the marks themselves remain the trademarks of their owners and are
// used to identify the service each connector talks to.
//
// ${entries.length} of ${connectors.length} connectors have a mark. The rest
// render as a monogram, because their mark is not in a source this repo can
// redistribute. To give one a real logo, put an SVG at
// branding/connectors/<id>.svg and re-run the generator.
//
// Missing: ${missing.length ? missing.join(', ') : 'none'}

export interface BrandMark {
  path: string;
  hex: string;
  viewBox: string;
}

export const BRAND_MARKS: Record<string, BrandMark> = {
${body}
};
`;

writeFileSync(join(ROOT, 'src/resources/connector_icons.ts'), out);
console.log(`    ${entries.length} marks, ${missing.length} monogram fallbacks`);
if (missing.length) console.log(`    no mark: ${missing.join(', ')}`);
