#!/usr/bin/env bash
# Confirm every Chromium header Flux includes actually exists at the pinned tag.
#
# base/containers/contains.h does not exist in M152. Nothing here knew that:
# it is a header this fork has always been able to assume, the include reads
# correctly, and no other check looks at include paths - so it reached the
# user's machine and failed 334 targets into a build, six minutes in, with
# "file not found".
#
# That is the whole class. Chromium moves headers and deletes them, and every
# guess made from memory about what M152 has is a build the user pays for. A
# HEAD request against the pinned tag settles it in milliseconds.
#
# Three kinds of include are skipped, because they are not in Chromium's tree:
#   - chrome/browser/flux/...  is this repo, junctioned in
#   - chrome/grit/...          is generated by grit at build time
#   - *.mojom*.h               is generated by the mojom bindings generator
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

VERSION=$(sed -n 's/^CHROMIUM_VERSION=//p' chromium.version | tr -d ' \t\r')
[ -n "$VERSION" ] || { echo "No CHROMIUM_VERSION in chromium.version" >&2; exit 1; }

BASE="https://raw.githubusercontent.com/chromium/chromium/$VERSION"
CACHE="${TMPDIR:-/tmp}/flux-includes-$VERSION"
mkdir -p "$CACHE" || exit 1

# Only headers that look like a Chromium tree path: a lowercase top-level
# directory followed by a slash. Angle-bracket and same-directory includes are
# not ours to check.
mapfile -t includes < <(
  grep -rhno '#include "[a-z0-9_][a-z0-9_./-]*\.h"' \
       src/browser --include='*.cc' --include='*.h' \
    | sed 's/.*#include "//; s/"$//' \
    | grep '/' \
    | grep -vE '^chrome/browser/flux/' \
    | grep -vE '^chrome/grit/' \
    | grep -vE '\.mojom[^/]*\.h$' \
    | sort -u
)

if [ "${#includes[@]}" -eq 0 ]; then
  echo "No Chromium includes found under src/browser - check the pattern." >&2
  exit 1
fi

status=0
missing=0
checked=0
offline=0

for header in "${includes[@]}"; do
  # One file per header, holding the HTTP status. Present means already known.
  key="$CACHE/$(printf '%s' "$header" | tr '/' '_')"
  if [ -s "$key" ]; then
    code=$(cat "$key")
  else
    code=$(curl -sS -o /dev/null -w '%{http_code}' --head --retry 2 \
                "$BASE/$header" 2>/dev/null)
    # Only cache a definitive answer. A network blip cached as 000 would turn
    # this check into a permanent false failure.
    case "$code" in 200|404) printf '%s' "$code" > "$key" ;; esac
  fi

  checked=$((checked + 1))
  case "$code" in
    200) ;;
    404)
      echo "FAIL: $header does not exist in Chromium $VERSION." >&2
      grep -rn "#include \"$header\"" src/browser | sed 's/^/      /' >&2
      missing=$((missing + 1))
      status=1
      ;;
    *)
      offline=$((offline + 1))
      ;;
  esac
done

if [ "$offline" -gt 0 ]; then
  echo "Could not reach $offline of $checked headers - those are UNVERIFIED." >&2
  echo "Say so rather than claiming the includes resolve." >&2
fi

if [ $status -eq 0 ] && [ "$offline" -eq 0 ]; then
  echo "Includes OK ($checked Chromium headers exist at $VERSION)"
fi
exit $status
